# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: frontend

# The runtime the application uses.
type: "python:3.6"

# The build-time dependencies of the app.
dependencies:
    python:
       flask: '*'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      sleep 1

# The size of the persistent disk of the application (in MB).
disk: 256

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: python server.py
