name: frontend

type: "python:3.6"

dependencies:
    python:
        flask: '*'
        flask-bootstrap: '*'
        flask-nav: '*'
        flask-wtf: '*'
        flask-debug: '*'
        requests: "*"
        redis: '*'
        hvac: '*'

hooks:
    build: |
      sleep 1

disk: 256

web:
    commands:
        start: FLASK_APP=__init__.py flask run --with-threads -h 0.0.0.0 -p 8888

relationships:
    redis: 'redis:redis'
